/**
 * Modèles de rôles système (docs/04-securite-rbac-audit.md §3.7).
 * Clonés dans chaque tenant à sa création (`is_system = true`, `template_code` renseigné).
 * Les motifs acceptent des jokers ; ils sont développés via `expandPatterns`.
 */
import { expandPatterns, type PermissionKey } from './catalog';

export interface RoleTemplate {
  readonly code: string;
  readonly name: string;
  readonly description: string;
  /** MFA obligatoire par défaut (désactivable par le tenant avec audit). */
  readonly mfaRequired: boolean;
  readonly patterns: readonly string[];
}

const ORG_READ = ['org:*:read'] as const;
const OWN_SCHEDULE = ['hr:leave:read', 'hr:schedule:read'] as const;

export const ROLE_TEMPLATES: readonly RoleTemplate[] = [
  {
    code: 'tenant_admin',
    name: 'Administrateur de l’établissement',
    description: 'Utilisateurs, rôles, organisation et paramètres. Aucun accès clinique (séparation des tâches).',
    mfaRequired: true,
    patterns: [
      'iam:*:*',
      'org:*:*',
      'settings:*:*',
      // Annuaire des praticiens et agendas : configuration organisationnelle, sans accès aux rendez-vous nominatifs.
      'appointments:agenda:*',
      'patients:patient:read',
      'reports:*:read',
      'audit:log:read',
      'audit:log:export',
      'audit:alert:*',
      'audit:access_report:read',
    ],
  },
  {
    code: 'director',
    name: 'Directeur',
    description: 'Tableaux de bord et rapports agrégés, lecture de l’organisation et de l’audit.',
    mfaRequired: true,
    patterns: [
      ...ORG_READ,
      'iam:user:read',
      'iam:role:read',
      'iam:assignment:read',
      'settings:*:read',
      'billing:invoice:read',
      'billing:invoice:export',
      'accounting:*:read',
      'accounting:report:*',
      'hr:*:read',
      'inventory:*:read',
      'reports:*:*',
      'audit:log:read',
    ],
  },
  {
    code: 'doctor',
    name: 'Médecin',
    description: 'Consultations, prescriptions, dossier médical, rendez-vous.',
    mfaRequired: false,
    patterns: [
      ...ORG_READ,
      ...OWN_SCHEDULE,
      'patients:patient:read',
      'patients:patient:create',
      'patients:patient:update',
      'patients:patient:print',
      'patients:consent:read',
      'patients:consent:create',
      'appointments:appointment:read',
      'appointments:appointment:create',
      'appointments:appointment:update',
      'appointments:appointment:print',
      'appointments:agenda:*',
      'consultations:consultation:*',
      'consultations:diagnosis:*',
      'consultations:prescription:*',
      'consultations:medical_record:read',
      'consultations:medical_record:print',
      'nursing:*:read',
      'maternity:*:read',
      'inpatient:admission:*',
      'laboratory:order:*',
      'laboratory:result:read',
      'imaging:order:*',
      'imaging:report:read',
      'reports:dashboard:read',
      'breakglass:access:create',
    ],
  },
  {
    code: 'nurse',
    name: 'Infirmier / Infirmière',
    description: 'Soins infirmiers, constantes, administration des traitements.',
    mfaRequired: false,
    patterns: [
      ...ORG_READ,
      ...OWN_SCHEDULE,
      'patients:patient:read',
      'patients:patient:update',
      'patients:consent:read',
      'patients:consent:create',
      'appointments:appointment:read',
      'appointments:appointment:create',
      'appointments:appointment:update',
      'consultations:consultation:read',
      'consultations:prescription:read',
      'consultations:medical_record:read',
      'nursing:*:*',
      'maternity:*:read',
      'inpatient:admission:read',
      'inpatient:admission:update',
      'laboratory:order:*',
      'laboratory:result:read',
      'breakglass:access:create',
    ],
  },
  {
    code: 'midwife',
    name: 'Sage-femme',
    description: 'Suivi de grossesse, accouchements, nouveau-nés.',
    mfaRequired: false,
    patterns: [
      ...ORG_READ,
      ...OWN_SCHEDULE,
      'patients:patient:read',
      'patients:patient:create',
      'patients:patient:update',
      'patients:patient:print',
      'patients:consent:read',
      'patients:consent:create',
      'appointments:appointment:read',
      'appointments:appointment:create',
      'appointments:appointment:update',
      'consultations:consultation:read',
      'consultations:prescription:read',
      'consultations:prescription:create',
      'consultations:prescription:update',
      'consultations:medical_record:read',
      'consultations:medical_record:print',
      'nursing:care_plan:read',
      'nursing:care_plan:create',
      'nursing:care_plan:update',
      'nursing:vitals:*',
      'maternity:*:*',
      'inpatient:admission:read',
      'inpatient:admission:update',
      'laboratory:order:*',
      'laboratory:result:read',
      'breakglass:access:create',
    ],
  },
  {
    code: 'pharmacist',
    name: 'Pharmacien',
    description: 'Dispensation, médicaments, stocks pharmaceutiques.',
    mfaRequired: true,
    patterns: [
      ...ORG_READ,
      ...OWN_SCHEDULE,
      'patients:patient:read',
      'consultations:prescription:read',
      'consultations:prescription:print',
      'pharmacy:*:*',
      'inventory:*:read',
      'reports:report:read',
    ],
  },
  {
    code: 'lab_technician',
    name: 'Technicien de laboratoire',
    description: 'Prélèvements et saisie des résultats (validation réservée au biologiste).',
    mfaRequired: false,
    patterns: [
      ...ORG_READ,
      ...OWN_SCHEDULE,
      'patients:patient:read',
      'appointments:appointment:read',
      'laboratory:order:read',
      'laboratory:sample:*',
      'laboratory:result:read',
      'laboratory:result:create',
      'laboratory:result:update',
      'laboratory:result:print',
      'reports:report:read',
    ],
  },
  {
    code: 'receptionist',
    name: 'Réceptionniste',
    description: 'Accueil, enregistrement des patients, rendez-vous, files d’attente.',
    mfaRequired: false,
    patterns: [
      ...ORG_READ,
      ...OWN_SCHEDULE,
      'patients:patient:read',
      'patients:patient:create',
      'patients:patient:update',
      'patients:patient:print',
      'patients:consent:*',
      'appointments:appointment:read',
      'appointments:appointment:create',
      'appointments:appointment:update',
      'appointments:appointment:print',
      'appointments:agenda:*',
      'inpatient:admission:read',
      'inpatient:admission:create',
      'billing:invoice:read',
      'billing:price_list:read',
      'billing:invoice:create',
      'billing:invoice:print',
      'billing:insurance_claim:read',
      'billing:insurance_claim:create',
    ],
  },
  {
    code: 'admin_agent',
    name: 'Agent administratif',
    description: 'Gestion administrative des dossiers, rendez-vous et facturation.',
    mfaRequired: false,
    patterns: [
      ...ORG_READ,
      'hr:leave:read',
      'hr:schedule:read',
      'hr:employee:read',
      'patients:patient:read',
      'patients:patient:create',
      'patients:patient:update',
      'patients:patient:print',
      'patients:consent:*',
      'appointments:appointment:read',
      'appointments:appointment:create',
      'appointments:appointment:update',
      'appointments:appointment:print',
      'appointments:agenda:*',
      'inpatient:admission:read',
      'inpatient:admission:create',
      'billing:invoice:read',
      'billing:price_list:read',
      'billing:invoice:create',
      'billing:invoice:update',
      'billing:invoice:print',
      'billing:insurance_claim:read',
      'billing:insurance_claim:create',
      'reports:report:read',
    ],
  },
  {
    code: 'accountant',
    name: 'Comptable',
    description: 'Comptabilité SYSCOHADA, facturation, contrôle de caisse.',
    mfaRequired: true,
    patterns: [
      ...ORG_READ,
      'patients:patient:read',
      'billing:invoice:read',
      'billing:price_list:read',
      'billing:price_list:update',
      'billing:invoice:create',
      'billing:invoice:update',
      'billing:invoice:validate',
      'billing:invoice:print',
      'billing:invoice:export',
      'billing:insurance_claim:read',
      'billing:insurance_claim:validate',
      'billing:insurance_claim:export',
      'cashier:payment:read',
      'cashier:cash_session:read',
      'cashier:cash_session:validate',
      'cashier:refund:validate',
      'accounting:*:*',
      'hr:payroll:read',
      'pharmacy:drug:read',
      'pharmacy:stock_movement:read',
      'inventory:*:read',
      'reports:*:*',
    ],
  },
  {
    code: 'hr_manager',
    name: 'Responsable RH',
    description: 'Dossiers du personnel, contrats, plannings, congés, paie.',
    mfaRequired: true,
    patterns: [...ORG_READ, 'iam:user:read', 'hr:*:*', 'reports:report:read'],
  },
  {
    code: 'stock_manager',
    name: 'Gestionnaire de stock',
    description: 'Produits, commandes, réceptions, inventaires.',
    mfaRequired: false,
    patterns: [
      ...ORG_READ,
      ...OWN_SCHEDULE,
      'pharmacy:drug:read',
      'pharmacy:stock_movement:read',
      'pharmacy:stock_movement:create',
      'inventory:*:*',
      'reports:report:read',
    ],
  },
  {
    code: 'cashier',
    name: 'Caissier',
    description: 'Encaissements, sessions de caisse, remboursements (validés par un autre rôle).',
    mfaRequired: false,
    patterns: [
      ...ORG_READ,
      ...OWN_SCHEDULE,
      'patients:patient:read',
      'appointments:appointment:read',
      'billing:invoice:read',
      'billing:price_list:read',
      'billing:invoice:create',
      'billing:invoice:print',
      'cashier:payment:*',
      'cashier:cash_session:read',
      'cashier:cash_session:create',
      'cashier:refund:create',
      'reports:report:read',
    ],
  },
];

export function permissionsForTemplate(template: RoleTemplate): PermissionKey[] {
  return expandPatterns(template.patterns);
}

export function findRoleTemplate(code: string): RoleTemplate | undefined {
  return ROLE_TEMPLATES.find((t) => t.code === code);
}
